apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: github-explorer
  namespace: github-explorer
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-github-explorer
    namespace: flux-system
  path: ./apps/github-explorer
  prune: true
  timeout: 5m
